# -*- coding: utf-8 -*-
"""EXAMPLE.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ic7DE17HT3jSqmz5Qw44W70gzPwtrKiX

# Connecting the library from GitHub
"""

!git clone https://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@github.com/MKJenna/Recognition_of_electric_circuits

cd '/content/Recognition_of_electric_circuits'

pwd

!pip install easyocr

"""Importing all functions"""

from circuits_recognition import *

"""# Element recognition"""

ex = '/content/drive/MyDrive/Colab Notebooks/C116_D2_P1.jpg'
ex2 = '/content/drive/MyDrive/Colab Notebooks/C151_D2_P3.jpg'
df = detect_elements(ex)
df

df2 = detect_elements(ex2, p=0.6)
df2

"""Write a question mark ($?$) and the name of the function you are interested in to get more information about the parameters:"""

?detect_elements

"""# Displaying elements in the image"""

draw_boxes(ex, df, ['all'], display_names=True)

draw_boxes(ex, df, ['or', 'and'], display_names=True)

draw_boxes(ex2, df2, ['all'], display_names=True)

"""# Recognizing text in an image

Text recognition takes 1 to 5 minutes.
"""

df_with_text = text_recognition(ex, df)
df_with_text